services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: my-cluster
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
